controllers_api:
    resource: ../../src/Controller/Api
    type: annotation

controllers_bo:
    resource: ../../src/Controller/Bo
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
